import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google'
import { ClerkProvider } from "@clerk/nextjs";

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Buntly",
  description: "Generated by create next app",
};

const clerkPubKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;

if (!clerkPubKey) {
  throw new Error("Missing Clerk publishable key");
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider publishableKey={clerkPubKey}>

        <body
          className={`${poppins.className} antialiased`}
        >
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}
